nurion4hep/HEP-CNN

scripts/preprocess.py
Minor update for better argparse usage.
=> Minor update to preprocessor

run/train_keras.py, scripts/preprocess.py
* simple runtime error fix caused by #4 
* Add training code with Keras
=> Preprocess fix & keras training code

run/train_keras.py, scripts/preprocess.py
Can write TFRecords (aware of large file size, though)
=> Use TFRecords

run/train_keras.py
Monitoring for the training steps.
=> monitor keras training

models/keras/default.py, run/train_keras.py
Split model from the main training script - for future extension
=> split model from training script

scripts/monitor_proc.py
the script can monitor CPU utilization.
Reference:
Meaning of fields in /proc/stat and /proc/<PROC ID>/stat etc.
http://www.dreamy.pe.kr/zbxe/CodeClip/163339
How to calculate CPU utilization from /proc files which are in "jiffy" time units
https://stackoverflow.com/questions/3503879/assign-output-of-os-system-to-a-variable-and-prevent-it-from-being-displayed-on
=> monitor cpu usage per 10s

scripts/monitor_proc.py
Rewrite with class, to be called from other scripts
=> Rewrite monitoring script

run/train_keras.py, scripts/monitor_proc.py
Improved performance monitoring
- Keep CPU utilization etc for each batch using keras callback
- Switch (back) to CSV module, not use pandas
- Better standalone script
=> Improve performance monitoring

models/HEPCNN/keras_default.py, run/train_keras.py
Separate model file, better monitoring
=> Separate model file, better monitoring

run/train_keras.py, scripts/monitor_proc.py
Better CUP utilization monitoring, train_keras automatically spawn monitring script
=> Better CPU utilization logging

run/drawPerfHistory.py
=> draw CPU usage plots

run/run_nurion.sh, run/train_keras.py
New run script for nurion system.
=> new run script, MT optimization

run/drawPerfHistory.py, run/train_keras.py
Minor update in plotting performance vs time
=> Better plotting

run/drawPerfHistory.py
=> better plotting styles

run/train_keras.py, run/train_torch.py, scripts/preprocess.py
Preprocessor properly saves npz with suffix
=> Preprocessor properly saves npz with suffix

run/train_torch.py
Determine suffix automatically.
=> determine suffix automatically

python/HEPCNN/keras_dataGenerator.py, python/HEPCNN/torch_dataset.py, run/train_torch.py, scripts/preprocess.py
Pytorch version is revised. 
Allow user defined chunk size in hdf5 file.
=> Fix Pytorch version + custom chunk size in hdf5 

run/drawLossCurve.py, run/drawPerfHistory.py, run/train_torch.py
Update performance plotting script, 
New loss curve plotting script,
torch training saves best model at the end of the process
=> Update performance plotting script, torch save best model 

python/HEPCNN/keras_dataGenerator.py, run/drawPerfHistory.py, run/train_keras.py, run/train_torch.py
per-second performance was hidden due to a bug.
=> Bugfix drawing resource usage performance

run/train_keras.py, run/train_torch.py
=> Horovod interface

examples/run_pytorch-mpicall-only.sh, run/drawPerfHistory.py, run/train_keras.py
Better plotting for performance monitoring,
keras horovod is working at nurion.
=> Better plotting, keras horovod 

run/train_torch.py, scripts/monitor_proc.py
1080ti needs smaller batch size. 
avoid division by zero exception, happens in local machine.
=> run at 1080ti, avoid div by zero error

run/drawLossCurve.py, run/drawPerfHistory.py, run/run_nurion.sh, run/train_keras.py
=> Benchmarks on KNL

run/train_keras.py, scripts/preprocess.py
Updates for performance tunings
=> Minor updates for tuning

run/drawPerfHistory.py, run/run_nurion.sh, run/train_keras.py, run/train_torch.py
=> Change output file name

run/train_keras.py
Explicitly set the TF session.
=> Explicitly set the tf session

run/train_keras.py, run/train_torch.py
=> log checkponits at epoch begins

run/train_torch.py
multinode/large batch emulation by averaging batches
=> multinode emulation

run/run_keras_nurion.sh, run/run_torch_nurion.sh
latest options and minor tunings.
=> latest options to run on full dataset

scripts/split.py
1. colab에서는 돌아가는 것을 확인 했습니다.
2. preprocess에 넣은 것은 아닙니다.
=> add hdf5 spliting script

scripts/split.py
make the routine simpler. splitting is done after the preprocessing.
=> better hdf5 splitting

scripts/split.py
Fix error while slicing last image
=> bugfix splitting script

run/eval_torch.py, run/train_torch.py
=> Shuffling + Evaluation

run/eval_torch.py
Save and load evaluation results
=> save and load evaluation results

examples/install_torch_horovod.sh, run/train_torch.py
=> Anaconda script 

examples/install_torch_horovod.sh, run/drawLossCurve.py, run/drawPerfHistory.py
=> Better installation recipe, plotting, read gzipped csv

run/drawTimingPerEpoch.py
=> Timing per epoch plot

scripts/install_torch_nurion.sh
Fresh install pytorch at nurion
=> fresh install pytorch at nurion

run/run_torch_nurion.sh, scripts/install_torch_nurion.sh
Optimal build options, envvars
=> Optimal build options, envvars

python/HEPCNN/torch_model_default.py, run/train_torch.py
Apply log scaling (with base value 1e-5) during the training step.
=> apply log scaling during the training step

python/HEPCNN/torch_dataset_splited.py, scripts/preprocess.py
New HEPCNNSplitDataset which is capable to read splited hdf5 files
Note: multithreading does not work "properly"
- CPU usage does not go up with nWorkers
- most probably due to the python GIL.
Hope to have new idea later...
=> New HEPCNNSplitDataset to read splited hdf5

run/train_torch.py, scripts/preprocess.py
Bugfix in preprocessing script
=> Bugfix preprocess

python/HEPCNN/torch_model_default.py
There was bug in the indexing.
=> Bugfix applying log scaling on the fly

python/HEPCNN/torch_model_original.py, run/train_torch.py
Add original model of the reference nersc model.
=> Add "original" model

python/HEPCNN/torch_model_circpad.py, python/HEPCNN/torch_model_original.py, run/train_torch.py
=> Implement circular padding

python/HEPCNN/torch_model_default.py
suggested from a blog article
https://gaussian37.github.io/dl-concept-order_of_regularization_term/
or stackoverflow discussion 
https://stackoverflow.com/questions/39691902/ordering-of-batch-normalization-and-dropout#answer-40295999
=> apply relu after BN and pool

run/eval_torch.py, run/train_torch.py
save the entrire model during the training step, load it during the evaluation step
=> Fix evaluation step

python/HEPCNN/torch_model_circpad.py
=> missing fix index

run/train_torch.py
Set number of reader processes
=> set number of readers

scripts/preprocess.py
Bugfix the last file was skipped.
Add debug option to simplify output message.
=> Bugfix do not skip last file

prod/cards/CMS_32PU.tcl, prod/cards/CMS_noPU.tcl, prod/run.sh, prod/src/weights.py, prod/submit.jds
minor fixes for the hdf production at condor farm
=> Minor fix for the hdf production at condor farm

run/train_labelByUser.py
insert missing code : adding large kernel model on the build model part
=> Select Large kernel models

run/train_labelByUser.py
=> fix wrong sign to keep the best weight

python/optimizers/lamb.py, python/optimizers/lars.py, python/optimizers/novograd.py, run/train_labelByUser.py
https://github.com/jettify/pytorch-optimizer 의 코드들을 사용하여 lamb, novograd를 추가하였고 https://github.com/kakaobrain/torchlars의 코드를 사용하여 lars 를 추가하였습니다. 
train_labelByIUser.py --optimizer 옵션에 lamb와 novograd 를 추가하였고, --lars 옵션을 생성하여 LARS로 base optimizer를 wrap 할지 말지 선택 할 수 있도록 만들었습니다.
lamb와 novograd의 경우 이미 .py 스크립트로 다 완성이 되어있어서 그냥 추가를 하면 되었으나, lars의 경우 본인들이 만든 torchlars 라이브러리에서 "compute_adaptive_lr" 이라는 함수를 불러와서 lr 계산에 사용하는 방식으로 만들어져 있었습니다. 해당 라이브러리를 참조하려고 보니 c++로 작성된 함수들을 .so 파일로 바꿔 사용하는 것 같아 모든 내용을 파악 하지 못했습니다. 그래서 해당 코드들에서 adaptive_lr을 계산하는 부분만 가져와서 lars.py 내부에 파이썬 언어로 작성해두었고, 학습이 되는 것을 확인했습니다. 
다만 제가 lars.py 내부 코드들과 c++로 작성된 adaptive_lr 계산하는 라이브러리를 완전히 이해하고 만든 것이 아니라 어떤 문제가 있을지 파악을 다 하지는 못했습니다. 이 부분은 꾸준히 코드와 학습 결과들을 보고 체크해보도록 하겠습니다.
=> add new optimizers lamb, novograd, lars (need to check lars)

run/train_labelByUser.py, scripts/install_torch_nurion.sh, scripts/setup.sh
Setup scripts to run at nurion
=> Setup scripts at nurion

run/train_labelByUser.py
Do not create performance monitoring subprocess, to reduce overhead - could help at very large scale.
=> Option to turn off performance monitoring subprocess

scripts/makeDetectorImage.py
Delphes root file에서 바로 3channel image를 만들 수 있는 script를 새로 구현함.
실행 시간 (RPV susy signal sample)
```
@@@ Finished processing...
Number of input files   = 23
Number of input events  = 330599
Number of output files  = 18
Number of output events = 294762
real	35m5.295s
user	13m22.545s
sys	21m38.131s
```
=> Build hdf image from root files

scripts/preprocess.py
Reimplement preprocessor with python class
=> New preprocessor

scripts/makeDetectorImage.py
makeDetectorImage.py로 생성한 h5 이미지 pixel value를 기존 데이터와 일치하도록 1000배 곱해주었습니다. (track cnt의 경우 hacl, ecal만 1000배)
=> makeDetectorImage.py modify
